### ISSUE TITLE
Should I move the "Git Started" doc I made in the CRPTools repository to the PSD GitHub Organization

### ISSUE THREAD

**Issue by sfregosi** [PIFSC-Protected-Species-Division/PSDOS#1]
In the hub on the first page @amandalbradford has linked to [this doc](https://github.com/sfregosi/CRPTools/blob/main/docs/git_started.md) I made to try to explain how to get set up with Git/GitHub. 

Also, @camrynallen made a great diagram that sketches out how this works that she plans to share with her peeps. 

I'm very happy to move my doc to a repository under the PSD GitHub Organization if people think that makes sense. What should it be called? Or should it just live within the PSDOS repository (could make that existing document into its own Quarto page)? 

Wondering what people think and how we can best share these sorts of resources!

**Comment by amandalbradford** [comment]
Good question @sfregosi! At this point, I don't have a strong feeling about where the local resources are as long as they can be accessed from the Hub page. I would lean toward _not_ putting it in the PSDOS repository (and making it a Hub page), as I like the idea of keeping that very streamlined, but maybe that is not necessary? If we feel like we are assembling enough odds and ends material like this, perhaps its worth starting a separate repository for them? I definitely like the idea of something being developed as a Division or Center tool (e.g., the abundance estimation package we are working on) being on the PSD Org, but I'm not sure beyond that. It will be interesting to work that out. I wonder what others think as well!

**Comment by sfregosi** [comment]
I did end up moving it here, into a folder called 'files' which I think can house external documentation that is not directly part of the web content. I had to make the CRPTools repository private (because it now houses some documentation about access the VPN, etc and I wasn't sure if that should be public, so in order to keep access to the Git Started as public as possible I moved it here. I also updated the link so it should still map from the main page correctly.

**Comment by amandalbradford** [comment]
Thanks @sfregosi, that works! It looks like the screenshot in the .md file is missing, so maybe that needs to be moved over also? I'm really looking forward to spending more time working on the Hub and hope others get excited about it, too!

**Comment by sfregosi** [comment]
Ah yes, thanks for catching that! All fixed now.
